name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code (comme un git clone mais optimisé pour GitHub Actions et avec des tokens d'accès)
      - name: Checkout dépôt
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lancer les tests
        working-directory: src
        run: |
          pytest
